-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.CheckRunStateCount exposing (..)

import Api.Enum.CheckRunState
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The number of check runs with this state.
-}
count : SelectionSet Int Api.Object.CheckRunStateCount
count =
    Object.selectionForField "Int" "count" [] Decode.int


{-| The state of a check run.
-}
state : SelectionSet Api.Enum.CheckRunState.CheckRunState Api.Object.CheckRunStateCount
state =
    Object.selectionForField "Enum.CheckRunState.CheckRunState" "state" [] Api.Enum.CheckRunState.decoder
