-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.CheckStep exposing (..)

import Api.Enum.CheckConclusionState
import Api.Enum.CheckStatusState
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the date and time when the check step was completed.
-}
completedAt : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.CheckStep
completedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "completedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


{-| The conclusion of the check step.
-}
conclusion : SelectionSet (Maybe Api.Enum.CheckConclusionState.CheckConclusionState) Api.Object.CheckStep
conclusion =
    Object.selectionForField "(Maybe Enum.CheckConclusionState.CheckConclusionState)" "conclusion" [] (Api.Enum.CheckConclusionState.decoder |> Decode.nullable)


{-| A reference for the check step on the integrator's system.
-}
externalId : SelectionSet (Maybe String) Api.Object.CheckStep
externalId =
    Object.selectionForField "(Maybe String)" "externalId" [] (Decode.string |> Decode.nullable)


{-| The step's name.
-}
name : SelectionSet String Api.Object.CheckStep
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The index of the step in the list of steps of the parent check run.
-}
number : SelectionSet Int Api.Object.CheckStep
number =
    Object.selectionForField "Int" "number" [] Decode.int


{-| Number of seconds to completion.
-}
secondsToCompletion : SelectionSet (Maybe Int) Api.Object.CheckStep
secondsToCompletion =
    Object.selectionForField "(Maybe Int)" "secondsToCompletion" [] (Decode.int |> Decode.nullable)


{-| Identifies the date and time when the check step was started.
-}
startedAt : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.CheckStep
startedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "startedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


{-| The current status of the check step.
-}
status : SelectionSet Api.Enum.CheckStatusState.CheckStatusState Api.Object.CheckStep
status =
    Object.selectionForField "Enum.CheckStatusState.CheckStatusState" "status" [] Api.Enum.CheckStatusState.decoder
