-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ClosedEvent exposing (..)

import Api.Enum.IssueStateReason
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the actor who performed the event.
-}
actor :
    SelectionSet decodesTo Api.Interface.Actor
    -> SelectionSet (Maybe decodesTo) Api.Object.ClosedEvent
actor object____ =
    Object.selectionForCompositeField "actor" [] object____ (Basics.identity >> Decode.nullable)


{-| Object that was closed.
-}
closable :
    SelectionSet decodesTo Api.Interface.Closable
    -> SelectionSet decodesTo Api.Object.ClosedEvent
closable object____ =
    Object.selectionForCompositeField "closable" [] object____ Basics.identity


{-| Object which triggered the creation of this event.
-}
closer :
    SelectionSet decodesTo Api.Union.Closer
    -> SelectionSet (Maybe decodesTo) Api.Object.ClosedEvent
closer object____ =
    Object.selectionForCompositeField "closer" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.ClosedEvent
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.ClosedEvent
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The HTTP path for this closed event.
-}
resourcePath : SelectionSet Api.ScalarCodecs.Uri Api.Object.ClosedEvent
resourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "resourcePath" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The reason the issue state was changed to closed.
-}
stateReason : SelectionSet (Maybe Api.Enum.IssueStateReason.IssueStateReason) Api.Object.ClosedEvent
stateReason =
    Object.selectionForField "(Maybe Enum.IssueStateReason.IssueStateReason)" "stateReason" [] (Api.Enum.IssueStateReason.decoder |> Decode.nullable)


{-| The HTTP URL for this closed event.
-}
url : SelectionSet Api.ScalarCodecs.Uri Api.Object.ClosedEvent
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)
