-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Cvss exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The CVSS score associated with this advisory
-}
score : SelectionSet Float Api.Object.Cvss
score =
    Object.selectionForField "Float" "score" [] Decode.float


{-| The CVSS vector string associated with this advisory
-}
vectorString : SelectionSet (Maybe String) Api.Object.Cvss
vectorString =
    Object.selectionForField "(Maybe String)" "vectorString" [] (Decode.string |> Decode.nullable)
