-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.DependabotUpdate exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The error from a dependency update
-}
error :
    SelectionSet decodesTo Api.Object.DependabotUpdateError
    -> SelectionSet (Maybe decodesTo) Api.Object.DependabotUpdate
error object____ =
    Object.selectionForCompositeField "error" [] object____ (Basics.identity >> Decode.nullable)


{-| The associated pull request
-}
pullRequest :
    SelectionSet decodesTo Api.Object.PullRequest
    -> SelectionSet (Maybe decodesTo) Api.Object.DependabotUpdate
pullRequest object____ =
    Object.selectionForCompositeField "pullRequest" [] object____ (Basics.identity >> Decode.nullable)


{-| The repository associated with this node.
-}
repository :
    SelectionSet decodesTo Api.Object.Repository
    -> SelectionSet decodesTo Api.Object.DependabotUpdate
repository object____ =
    Object.selectionForCompositeField "repository" [] object____ Basics.identity
