-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.DependabotUpdateError exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The body of the error
-}
body : SelectionSet String Api.Object.DependabotUpdateError
body =
    Object.selectionForField "String" "body" [] Decode.string


{-| The error code
-}
errorType : SelectionSet String Api.Object.DependabotUpdateError
errorType =
    Object.selectionForField "String" "errorType" [] Decode.string


{-| The title of the error
-}
title : SelectionSet String Api.Object.DependabotUpdateError
title =
    Object.selectionForField "String" "title" [] Decode.string
