-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.DeploymentProtectionRule exposing (..)

import Api.Enum.DeploymentProtectionRuleType
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe Int) Api.Object.DeploymentProtectionRule
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


type alias ReviewersOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| The teams or users that can review the deployment

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
reviewers :
    (ReviewersOptionalArguments -> ReviewersOptionalArguments)
    -> SelectionSet decodesTo Api.Object.DeploymentReviewerConnection
    -> SelectionSet decodesTo Api.Object.DeploymentProtectionRule
reviewers fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reviewers" optionalArgs____ object____ Basics.identity


{-| The timeout in minutes for this protection rule.
-}
timeout : SelectionSet Int Api.Object.DeploymentProtectionRule
timeout =
    Object.selectionForField "Int" "timeout" [] Decode.int


{-| The type of protection rule.
-}
type_ : SelectionSet Api.Enum.DeploymentProtectionRuleType.DeploymentProtectionRuleType Api.Object.DeploymentProtectionRule
type_ =
    Object.selectionForField "Enum.DeploymentProtectionRuleType.DeploymentProtectionRuleType" "type" [] Api.Enum.DeploymentProtectionRuleType.decoder
