-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.DiscussionPollOption exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Api.ScalarCodecs.Id Api.Object.DiscussionPollOption
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The text for this option.
-}
option : SelectionSet String Api.Object.DiscussionPollOption
option =
    Object.selectionForField "String" "option" [] Decode.string


{-| The discussion poll that this option belongs to.
-}
poll :
    SelectionSet decodesTo Api.Object.DiscussionPoll
    -> SelectionSet (Maybe decodesTo) Api.Object.DiscussionPollOption
poll object____ =
    Object.selectionForCompositeField "poll" [] object____ (Basics.identity >> Decode.nullable)


{-| The total number of votes that have been cast for this option.
-}
totalVoteCount : SelectionSet Int Api.Object.DiscussionPollOption
totalVoteCount =
    Object.selectionForField "Int" "totalVoteCount" [] Decode.int


{-| Indicates if the viewer has voted for this option in the poll.
-}
viewerHasVoted : SelectionSet Bool Api.Object.DiscussionPollOption
viewerHasVoted =
    Object.selectionForField "Bool" "viewerHasVoted" [] Decode.bool
