-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.DiscussionCategory exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.DiscussionCategory
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| A description of this category.
-}
description : SelectionSet (Maybe String) Api.Object.DiscussionCategory
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| An emoji representing this category.
-}
emoji : SelectionSet String Api.Object.DiscussionCategory
emoji =
    Object.selectionForField "String" "emoji" [] Decode.string


{-| This category's emoji rendered as HTML.
-}
emojiHTML : SelectionSet Api.ScalarCodecs.Html Api.Object.DiscussionCategory
emojiHTML =
    Object.selectionForField "ScalarCodecs.Html" "emojiHTML" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecHtml |> .decoder)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.DiscussionCategory
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether or not discussions in this category support choosing an answer with the markDiscussionCommentAsAnswer mutation.
-}
isAnswerable : SelectionSet Bool Api.Object.DiscussionCategory
isAnswerable =
    Object.selectionForField "Bool" "isAnswerable" [] Decode.bool


{-| The name of this category.
-}
name : SelectionSet String Api.Object.DiscussionCategory
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The repository associated with this node.
-}
repository :
    SelectionSet decodesTo Api.Object.Repository
    -> SelectionSet decodesTo Api.Object.DiscussionCategory
repository object____ =
    Object.selectionForCompositeField "repository" [] object____ Basics.identity


{-| The slug of this category.
-}
slug : SelectionSet String Api.Object.DiscussionCategory
slug =
    Object.selectionForField "String" "slug" [] Decode.string


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.DiscussionCategory
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
