-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.EnterprisePendingMemberInvitationConnection exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A list of edges.
-}
edges :
    SelectionSet decodesTo Api.Object.EnterprisePendingMemberInvitationEdge
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.EnterprisePendingMemberInvitationConnection
edges object____ =
    Object.selectionForCompositeField "edges" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| A list of nodes.
-}
nodes :
    SelectionSet decodesTo Api.Object.OrganizationInvitation
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.EnterprisePendingMemberInvitationConnection
nodes object____ =
    Object.selectionForCompositeField "nodes" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Information to aid in pagination.
-}
pageInfo :
    SelectionSet decodesTo Api.Object.PageInfo
    -> SelectionSet decodesTo Api.Object.EnterprisePendingMemberInvitationConnection
pageInfo object____ =
    Object.selectionForCompositeField "pageInfo" [] object____ Basics.identity


{-| Identifies the total count of items in the connection.
-}
totalCount : SelectionSet Int Api.Object.EnterprisePendingMemberInvitationConnection
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int


{-| Identifies the total count of unique users in the connection.
-}
totalUniqueUserCount : SelectionSet Int Api.Object.EnterprisePendingMemberInvitationConnection
totalUniqueUserCount =
    Object.selectionForField "Int" "totalUniqueUserCount" [] Decode.int
