-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ExternalIdentityScimAttributes exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The emails associated with the SCIM identity
-}
emails :
    SelectionSet decodesTo Api.Object.UserEmailMetadata
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.ExternalIdentityScimAttributes
emails object____ =
    Object.selectionForCompositeField "emails" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Family name of the SCIM identity
-}
familyName : SelectionSet (Maybe String) Api.Object.ExternalIdentityScimAttributes
familyName =
    Object.selectionForField "(Maybe String)" "familyName" [] (Decode.string |> Decode.nullable)


{-| Given name of the SCIM identity
-}
givenName : SelectionSet (Maybe String) Api.Object.ExternalIdentityScimAttributes
givenName =
    Object.selectionForField "(Maybe String)" "givenName" [] (Decode.string |> Decode.nullable)


{-| The groups linked to this identity in IDP
-}
groups : SelectionSet (Maybe (List String)) Api.Object.ExternalIdentityScimAttributes
groups =
    Object.selectionForField "(Maybe (List String))" "groups" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| The userName of the SCIM identity
-}
username : SelectionSet (Maybe String) Api.Object.ExternalIdentityScimAttributes
username =
    Object.selectionForField "(Maybe String)" "username" [] (Decode.string |> Decode.nullable)
