-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ExternalIdentitySamlAttributes exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| SAML Identity attributes
-}
attributes :
    SelectionSet decodesTo Api.Object.ExternalIdentityAttribute
    -> SelectionSet (List decodesTo) Api.Object.ExternalIdentitySamlAttributes
attributes object____ =
    Object.selectionForCompositeField "attributes" [] object____ (Basics.identity >> Decode.list)


{-| The emails associated with the SAML identity
-}
emails :
    SelectionSet decodesTo Api.Object.UserEmailMetadata
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.ExternalIdentitySamlAttributes
emails object____ =
    Object.selectionForCompositeField "emails" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Family name of the SAML identity
-}
familyName : SelectionSet (Maybe String) Api.Object.ExternalIdentitySamlAttributes
familyName =
    Object.selectionForField "(Maybe String)" "familyName" [] (Decode.string |> Decode.nullable)


{-| Given name of the SAML identity
-}
givenName : SelectionSet (Maybe String) Api.Object.ExternalIdentitySamlAttributes
givenName =
    Object.selectionForField "(Maybe String)" "givenName" [] (Decode.string |> Decode.nullable)


{-| The groups linked to this identity in IDP
-}
groups : SelectionSet (Maybe (List String)) Api.Object.ExternalIdentitySamlAttributes
groups =
    Object.selectionForField "(Maybe (List String))" "groups" [] (Decode.string |> Decode.list |> Decode.nullable)


{-| The NameID of the SAML identity
-}
nameId : SelectionSet (Maybe String) Api.Object.ExternalIdentitySamlAttributes
nameId =
    Object.selectionForField "(Maybe String)" "nameId" [] (Decode.string |> Decode.nullable)


{-| The userName of the SAML identity
-}
username : SelectionSet (Maybe String) Api.Object.ExternalIdentitySamlAttributes
username =
    Object.selectionForField "(Maybe String)" "username" [] (Decode.string |> Decode.nullable)
