-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.OrganizationEnterpriseOwnerEdge exposing (..)

import Api.Enum.RoleInOrganization
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A cursor for use in pagination.
-}
cursor : SelectionSet String Api.Object.OrganizationEnterpriseOwnerEdge
cursor =
    Object.selectionForField "String" "cursor" [] Decode.string


{-| The item at the end of the edge.
-}
node :
    SelectionSet decodesTo Api.Object.User
    -> SelectionSet (Maybe decodesTo) Api.Object.OrganizationEnterpriseOwnerEdge
node object____ =
    Object.selectionForCompositeField "node" [] object____ (Basics.identity >> Decode.nullable)


{-| The role of the owner with respect to the organization.
-}
organizationRole : SelectionSet Api.Enum.RoleInOrganization.RoleInOrganization Api.Object.OrganizationEnterpriseOwnerEdge
organizationRole =
    Object.selectionForField "Enum.RoleInOrganization.RoleInOrganization" "organizationRole" [] Api.Enum.RoleInOrganization.decoder
