-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ProjectView exposing (..)

import Api.Enum.ProjectViewLayout
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifies the date and time when the object was created.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.ProjectView
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Identifies the primary key from the database.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
databaseId : SelectionSet (Maybe Int) Api.Object.ProjectView
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


{-| The project view's filter.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
filter : SelectionSet (Maybe String) Api.Object.ProjectView
filter =
    Object.selectionForField "(Maybe String)" "filter" [] (Decode.string |> Decode.nullable)


{-| The view's group-by field.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
groupBy : SelectionSet (Maybe (List Int)) Api.Object.ProjectView
groupBy =
    Object.selectionForField "(Maybe (List Int))" "groupBy" [] (Decode.int |> Decode.list |> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.ProjectView
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The project view's layout.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
layout : SelectionSet Api.Enum.ProjectViewLayout.ProjectViewLayout Api.Object.ProjectView
layout =
    Object.selectionForField "Enum.ProjectViewLayout.ProjectViewLayout" "layout" [] Api.Enum.ProjectViewLayout.decoder


{-| The project view's name.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
name : SelectionSet String Api.Object.ProjectView
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The project view's number.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
number : SelectionSet Int Api.Object.ProjectView
number =
    Object.selectionForField "Int" "number" [] Decode.int


{-| The project that contains this view.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
project :
    SelectionSet decodesTo Api.Object.ProjectNext
    -> SelectionSet decodesTo Api.Object.ProjectView
project object____ =
    Object.selectionForCompositeField "project" [] object____ Basics.identity


{-| The view's sort-by config.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
sortBy :
    SelectionSet decodesTo Api.Object.SortBy
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.ProjectView
sortBy object____ =
    Object.selectionForCompositeField "sortBy" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Identifies the date and time when the object was last updated.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.ProjectView
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The view's vertical-group-by field.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
verticalGroupBy : SelectionSet (Maybe (List Int)) Api.Object.ProjectView
verticalGroupBy =
    Object.selectionForField "(Maybe (List Int))" "verticalGroupBy" [] (Decode.int |> Decode.list |> Decode.nullable)


{-| The view's visible fields.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.
-}
visibleFields : SelectionSet (Maybe (List Int)) Api.Object.ProjectView
visibleFields =
    Object.selectionForField "(Maybe (List Int))" "visibleFields" [] (Decode.int |> Decode.list |> Decode.nullable)
