-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PullRequest exposing (..)

import Api.Enum.CommentAuthorAssociation
import Api.Enum.CommentCannotUpdateReason
import Api.Enum.LockReason
import Api.Enum.MergeableState
import Api.Enum.ProjectCardArchivedState
import Api.Enum.ProjectNextOrderField
import Api.Enum.PullRequestMergeMethod
import Api.Enum.PullRequestReviewDecision
import Api.Enum.PullRequestReviewState
import Api.Enum.PullRequestState
import Api.Enum.PullRequestTimelineItemsItemType
import Api.Enum.ReactionContent
import Api.Enum.SubscriptionState
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Reason that the conversation was locked.
-}
activeLockReason : SelectionSet (Maybe Api.Enum.LockReason.LockReason) Api.Object.PullRequest
activeLockReason =
    Object.selectionForField "(Maybe Enum.LockReason.LockReason)" "activeLockReason" [] (Api.Enum.LockReason.decoder |> Decode.nullable)


{-| The number of additions in this pull request.
-}
additions : SelectionSet Int Api.Object.PullRequest
additions =
    Object.selectionForField "Int" "additions" [] Decode.int


type alias AssigneesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of Users assigned to this object.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
assignees :
    (AssigneesOptionalArguments -> AssigneesOptionalArguments)
    -> SelectionSet decodesTo Api.Object.UserConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
assignees fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "assignees" optionalArgs____ object____ Basics.identity


{-| The actor who authored the comment.
-}
author :
    SelectionSet decodesTo Api.Interface.Actor
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
author object____ =
    Object.selectionForCompositeField "author" [] object____ (Basics.identity >> Decode.nullable)


{-| Author's association with the subject of the comment.
-}
authorAssociation : SelectionSet Api.Enum.CommentAuthorAssociation.CommentAuthorAssociation Api.Object.PullRequest
authorAssociation =
    Object.selectionForField "Enum.CommentAuthorAssociation.CommentAuthorAssociation" "authorAssociation" [] Api.Enum.CommentAuthorAssociation.decoder


{-| Returns the auto-merge request object if one exists for this pull request.
-}
autoMergeRequest :
    SelectionSet decodesTo Api.Object.AutoMergeRequest
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
autoMergeRequest object____ =
    Object.selectionForCompositeField "autoMergeRequest" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the base Ref associated with the pull request.
-}
baseRef :
    SelectionSet decodesTo Api.Object.Ref
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
baseRef object____ =
    Object.selectionForCompositeField "baseRef" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the name of the base Ref associated with the pull request, even if the ref has been deleted.
-}
baseRefName : SelectionSet String Api.Object.PullRequest
baseRefName =
    Object.selectionForField "String" "baseRefName" [] Decode.string


{-| Identifies the oid of the base ref associated with the pull request, even if the ref has been deleted.
-}
baseRefOid : SelectionSet Api.ScalarCodecs.GitObjectID Api.Object.PullRequest
baseRefOid =
    Object.selectionForField "ScalarCodecs.GitObjectID" "baseRefOid" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecGitObjectID |> .decoder)


{-| The repository associated with this pull request's base Ref.
-}
baseRepository :
    SelectionSet decodesTo Api.Object.Repository
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
baseRepository object____ =
    Object.selectionForCompositeField "baseRepository" [] object____ (Basics.identity >> Decode.nullable)


{-| The body as Markdown.
-}
body : SelectionSet String Api.Object.PullRequest
body =
    Object.selectionForField "String" "body" [] Decode.string


{-| The body rendered to HTML.
-}
bodyHTML : SelectionSet Api.ScalarCodecs.Html Api.Object.PullRequest
bodyHTML =
    Object.selectionForField "ScalarCodecs.Html" "bodyHTML" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecHtml |> .decoder)


{-| The body rendered to text.
-}
bodyText : SelectionSet String Api.Object.PullRequest
bodyText =
    Object.selectionForField "String" "bodyText" [] Decode.string


{-| The number of changed files in this pull request.
-}
changedFiles : SelectionSet Int Api.Object.PullRequest
changedFiles =
    Object.selectionForField "Int" "changedFiles" [] Decode.int


{-| The HTTP path for the checks of this pull request.
-}
checksResourcePath : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequest
checksResourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "checksResourcePath" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The HTTP URL for the checks of this pull request.
-}
checksUrl : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequest
checksUrl =
    Object.selectionForField "ScalarCodecs.Uri" "checksUrl" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| `true` if the pull request is closed
-}
closed : SelectionSet Bool Api.Object.PullRequest
closed =
    Object.selectionForField "Bool" "closed" [] Decode.bool


{-| Identifies the date and time when the object was closed.
-}
closedAt : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.PullRequest
closedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "closedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


type alias ClosingIssuesReferencesOptionalArguments =
    { userLinkedOnly : OptionalArgument Bool
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , orderBy : OptionalArgument Api.InputObject.IssueOrder
    }


{-| List of issues that were may be closed by this pull request

  - userLinkedOnly - Return only manually linked Issues
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - orderBy - Ordering options for issues returned from the connection

-}
closingIssuesReferences :
    (ClosingIssuesReferencesOptionalArguments -> ClosingIssuesReferencesOptionalArguments)
    -> SelectionSet decodesTo Api.Object.IssueConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
closingIssuesReferences fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { userLinkedOnly = Absent, after = Absent, before = Absent, first = Absent, last = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "userLinkedOnly" filledInOptionals____.userLinkedOnly Encode.bool, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "orderBy" filledInOptionals____.orderBy Api.InputObject.encodeIssueOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "closingIssuesReferences" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias CommentsOptionalArguments =
    { orderBy : OptionalArgument Api.InputObject.IssueCommentOrder
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of comments associated with the pull request.

  - orderBy - Ordering options for issue comments returned from the connection.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
comments :
    (CommentsOptionalArguments -> CommentsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.IssueCommentConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
comments fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "orderBy" filledInOptionals____.orderBy Api.InputObject.encodeIssueCommentOrder, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "comments" optionalArgs____ object____ Basics.identity


type alias CommitsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of commits present in this pull request's head branch not present in the base branch.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
commits :
    (CommitsOptionalArguments -> CommitsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestCommitConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
commits fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "commits" optionalArgs____ object____ Basics.identity


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.PullRequest
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Check if this comment was created via an email reply.
-}
createdViaEmail : SelectionSet Bool Api.Object.PullRequest
createdViaEmail =
    Object.selectionForField "Bool" "createdViaEmail" [] Decode.bool


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe Int) Api.Object.PullRequest
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


{-| The number of deletions in this pull request.
-}
deletions : SelectionSet Int Api.Object.PullRequest
deletions =
    Object.selectionForField "Int" "deletions" [] Decode.int


{-| The actor who edited this pull request's body.
-}
editor :
    SelectionSet decodesTo Api.Interface.Actor
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
editor object____ =
    Object.selectionForCompositeField "editor" [] object____ (Basics.identity >> Decode.nullable)


type alias FilesOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| Lists the files changed within this pull request.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
files :
    (FilesOptionalArguments -> FilesOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestChangedFileConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
files fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "files" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| Identifies the head Ref associated with the pull request.
-}
headRef :
    SelectionSet decodesTo Api.Object.Ref
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
headRef object____ =
    Object.selectionForCompositeField "headRef" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the name of the head Ref associated with the pull request, even if the ref has been deleted.
-}
headRefName : SelectionSet String Api.Object.PullRequest
headRefName =
    Object.selectionForField "String" "headRefName" [] Decode.string


{-| Identifies the oid of the head ref associated with the pull request, even if the ref has been deleted.
-}
headRefOid : SelectionSet Api.ScalarCodecs.GitObjectID Api.Object.PullRequest
headRefOid =
    Object.selectionForField "ScalarCodecs.GitObjectID" "headRefOid" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecGitObjectID |> .decoder)


{-| The repository associated with this pull request's head Ref.
-}
headRepository :
    SelectionSet decodesTo Api.Object.Repository
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
headRepository object____ =
    Object.selectionForCompositeField "headRepository" [] object____ (Basics.identity >> Decode.nullable)


{-| The owner of the repository associated with this pull request's head Ref.
-}
headRepositoryOwner :
    SelectionSet decodesTo Api.Interface.RepositoryOwner
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
headRepositoryOwner object____ =
    Object.selectionForCompositeField "headRepositoryOwner" [] object____ (Basics.identity >> Decode.nullable)


type alias HovercardOptionalArguments =
    { includeNotificationContexts : OptionalArgument Bool }


{-| The hovercard information for this issue

  - includeNotificationContexts - Whether or not to include notification contexts

-}
hovercard :
    (HovercardOptionalArguments -> HovercardOptionalArguments)
    -> SelectionSet decodesTo Api.Object.Hovercard
    -> SelectionSet decodesTo Api.Object.PullRequest
hovercard fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { includeNotificationContexts = Absent }

        optionalArgs____ =
            [ Argument.optional "includeNotificationContexts" filledInOptionals____.includeNotificationContexts Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "hovercard" optionalArgs____ object____ Basics.identity


id : SelectionSet Api.ScalarCodecs.Id Api.Object.PullRequest
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Check if this comment was edited and includes an edit with the creation data
-}
includesCreatedEdit : SelectionSet Bool Api.Object.PullRequest
includesCreatedEdit =
    Object.selectionForField "Bool" "includesCreatedEdit" [] Decode.bool


{-| The head and base repositories are different.
-}
isCrossRepository : SelectionSet Bool Api.Object.PullRequest
isCrossRepository =
    Object.selectionForField "Bool" "isCrossRepository" [] Decode.bool


{-| Identifies if the pull request is a draft.
-}
isDraft : SelectionSet Bool Api.Object.PullRequest
isDraft =
    Object.selectionForField "Bool" "isDraft" [] Decode.bool


{-| Is this pull request read by the viewer
-}
isReadByViewer : SelectionSet (Maybe Bool) Api.Object.PullRequest
isReadByViewer =
    Object.selectionForField "(Maybe Bool)" "isReadByViewer" [] (Decode.bool |> Decode.nullable)


type alias LabelsOptionalArguments =
    { orderBy : OptionalArgument Api.InputObject.LabelOrder
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of labels associated with the object.

  - orderBy - Ordering options for labels returned from the connection.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
labels :
    (LabelsOptionalArguments -> LabelsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.LabelConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
labels fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "orderBy" filledInOptionals____.orderBy Api.InputObject.encodeLabelOrder, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "labels" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| The moment the editor made the last edit
-}
lastEditedAt : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.PullRequest
lastEditedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "lastEditedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


type alias LatestOpinionatedReviewsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , writersOnly : OptionalArgument Bool
    }


{-| A list of latest reviews per user associated with the pull request.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - writersOnly - Only return reviews from user who have write access to the repository

-}
latestOpinionatedReviews :
    (LatestOpinionatedReviewsOptionalArguments -> LatestOpinionatedReviewsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestReviewConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
latestOpinionatedReviews fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, writersOnly = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "writersOnly" filledInOptionals____.writersOnly Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "latestOpinionatedReviews" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias LatestReviewsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of latest reviews per user associated with the pull request that are not also pending review.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
latestReviews :
    (LatestReviewsOptionalArguments -> LatestReviewsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestReviewConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
latestReviews fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "latestReviews" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| `true` if the pull request is locked
-}
locked : SelectionSet Bool Api.Object.PullRequest
locked =
    Object.selectionForField "Bool" "locked" [] Decode.bool


{-| Indicates whether maintainers can modify the pull request.
-}
maintainerCanModify : SelectionSet Bool Api.Object.PullRequest
maintainerCanModify =
    Object.selectionForField "Bool" "maintainerCanModify" [] Decode.bool


{-| The commit that was created when this pull request was merged.
-}
mergeCommit :
    SelectionSet decodesTo Api.Object.Commit
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
mergeCommit object____ =
    Object.selectionForCompositeField "mergeCommit" [] object____ (Basics.identity >> Decode.nullable)


{-| Whether or not the pull request can be merged based on the existence of merge conflicts.
-}
mergeable : SelectionSet Api.Enum.MergeableState.MergeableState Api.Object.PullRequest
mergeable =
    Object.selectionForField "Enum.MergeableState.MergeableState" "mergeable" [] Api.Enum.MergeableState.decoder


{-| Whether or not the pull request was merged.
-}
merged : SelectionSet Bool Api.Object.PullRequest
merged =
    Object.selectionForField "Bool" "merged" [] Decode.bool


{-| The date and time that the pull request was merged.
-}
mergedAt : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.PullRequest
mergedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "mergedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


{-| The actor who merged the pull request.
-}
mergedBy :
    SelectionSet decodesTo Api.Interface.Actor
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
mergedBy object____ =
    Object.selectionForCompositeField "mergedBy" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the milestone associated with the pull request.
-}
milestone :
    SelectionSet decodesTo Api.Object.Milestone
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
milestone object____ =
    Object.selectionForCompositeField "milestone" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the pull request number.
-}
number : SelectionSet Int Api.Object.PullRequest
number =
    Object.selectionForField "Int" "number" [] Decode.int


type alias ParticipantsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of Users that are participating in the Pull Request conversation.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
participants :
    (ParticipantsOptionalArguments -> ParticipantsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.UserConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
participants fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "participants" optionalArgs____ object____ Basics.identity


{-| The permalink to the pull request.
-}
permalink : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequest
permalink =
    Object.selectionForField "ScalarCodecs.Uri" "permalink" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The commit that GitHub automatically generated to test if this pull request could be merged. This field will not return a value if the pull request is merged, or if the test merge commit is still being generated. See the `mergeable` field for more details on the mergeability of the pull request.
-}
potentialMergeCommit :
    SelectionSet decodesTo Api.Object.Commit
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
potentialMergeCommit object____ =
    Object.selectionForCompositeField "potentialMergeCommit" [] object____ (Basics.identity >> Decode.nullable)


type alias ProjectCardsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , archivedStates : OptionalArgument (List (Maybe Api.Enum.ProjectCardArchivedState.ProjectCardArchivedState))
    }


{-| List of project cards associated with this pull request.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - archivedStates - A list of archived states to filter the cards by

-}
projectCards :
    (ProjectCardsOptionalArguments -> ProjectCardsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ProjectCardConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
projectCards fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, archivedStates = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "archivedStates" filledInOptionals____.archivedStates (Encode.enum Api.Enum.ProjectCardArchivedState.toString |> Encode.maybe |> Encode.list) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projectCards" optionalArgs____ object____ Basics.identity


type alias ProjectItemsOptionalArguments =
    { includeArchived : OptionalArgument Bool
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| List of project items associated with this pull request.

  - includeArchived - Include archived items.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
projectItems :
    (ProjectItemsOptionalArguments -> ProjectItemsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ProjectV2ItemConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
projectItems fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { includeArchived = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "includeArchived" filledInOptionals____.includeArchived Encode.bool, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projectItems" optionalArgs____ object____ Basics.identity


type alias ProjectNextRequiredArguments =
    { number : Int }


{-| Find a project by project (beta) number.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.

  - number - The project (beta) number.

-}
projectNext :
    ProjectNextRequiredArguments
    -> SelectionSet decodesTo Api.Object.ProjectNext
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
projectNext requiredArgs____ object____ =
    Object.selectionForCompositeField "projectNext" [ Argument.required "number" requiredArgs____.number Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias ProjectNextItemsOptionalArguments =
    { includeArchived : OptionalArgument Bool
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| List of project (beta) items associated with this pull request.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.

  - includeArchived - Include archived items.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
projectNextItems :
    (ProjectNextItemsOptionalArguments -> ProjectNextItemsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ProjectNextItemConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
projectNextItems fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { includeArchived = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "includeArchived" filledInOptionals____.includeArchived Encode.bool, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projectNextItems" optionalArgs____ object____ Basics.identity


type alias ProjectV2RequiredArguments =
    { number : Int }


{-| Find a project by number.

  - number - The project number.

-}
projectV2 :
    ProjectV2RequiredArguments
    -> SelectionSet decodesTo Api.Object.ProjectV2
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
projectV2 requiredArgs____ object____ =
    Object.selectionForCompositeField "projectV2" [ Argument.required "number" requiredArgs____.number Encode.int ] object____ (Basics.identity >> Decode.nullable)


type alias ProjectsNextOptionalArguments =
    { query : OptionalArgument String
    , sortBy : OptionalArgument Api.Enum.ProjectNextOrderField.ProjectNextOrderField
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of projects (beta) under the owner.
@deprecated The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at <https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/>, to find a suitable replacement. Removal on 2023-01-01 UTC.

  - query - A project (beta) to search for under the the owner.
  - sortBy - How to order the returned projects (beta).
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
projectsNext :
    (ProjectsNextOptionalArguments -> ProjectsNextOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ProjectNextConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
projectsNext fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { query = Absent, sortBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "query" filledInOptionals____.query Encode.string, Argument.optional "sortBy" filledInOptionals____.sortBy (Encode.enum Api.Enum.ProjectNextOrderField.toString), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projectsNext" optionalArgs____ object____ Basics.identity


type alias ProjectsV2OptionalArguments =
    { query : OptionalArgument String
    , orderBy : OptionalArgument Api.InputObject.ProjectV2Order
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of projects under the owner.

  - query - A project to search for under the the owner.
  - orderBy - How to order the returned projects.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
projectsV2 :
    (ProjectsV2OptionalArguments -> ProjectsV2OptionalArguments)
    -> SelectionSet decodesTo Api.Object.ProjectV2Connection
    -> SelectionSet decodesTo Api.Object.PullRequest
projectsV2 fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { query = Absent, orderBy = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "query" filledInOptionals____.query Encode.string, Argument.optional "orderBy" filledInOptionals____.orderBy Api.InputObject.encodeProjectV2Order, Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "projectsV2" optionalArgs____ object____ Basics.identity


{-| Identifies when the comment was published at.
-}
publishedAt : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.PullRequest
publishedAt =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "publishedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)


{-| A list of reactions grouped by content left on the subject.
-}
reactionGroups :
    SelectionSet decodesTo Api.Object.ReactionGroup
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.PullRequest
reactionGroups object____ =
    Object.selectionForCompositeField "reactionGroups" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


type alias ReactionsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , content : OptionalArgument Api.Enum.ReactionContent.ReactionContent
    , orderBy : OptionalArgument Api.InputObject.ReactionOrder
    }


{-| A list of Reactions left on the Issue.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - content - Allows filtering Reactions by emoji.
  - orderBy - Allows specifying the order in which reactions are returned.

-}
reactions :
    (ReactionsOptionalArguments -> ReactionsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ReactionConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
reactions fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, content = Absent, orderBy = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "content" filledInOptionals____.content (Encode.enum Api.Enum.ReactionContent.toString), Argument.optional "orderBy" filledInOptionals____.orderBy Api.InputObject.encodeReactionOrder ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reactions" optionalArgs____ object____ Basics.identity


{-| The repository associated with this node.
-}
repository :
    SelectionSet decodesTo Api.Object.Repository
    -> SelectionSet decodesTo Api.Object.PullRequest
repository object____ =
    Object.selectionForCompositeField "repository" [] object____ Basics.identity


{-| The HTTP path for this pull request.
-}
resourcePath : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequest
resourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "resourcePath" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The HTTP path for reverting this pull request.
-}
revertResourcePath : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequest
revertResourcePath =
    Object.selectionForField "ScalarCodecs.Uri" "revertResourcePath" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The HTTP URL for reverting this pull request.
-}
revertUrl : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequest
revertUrl =
    Object.selectionForField "ScalarCodecs.Uri" "revertUrl" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The current status of this pull request with respect to code review.
-}
reviewDecision : SelectionSet (Maybe Api.Enum.PullRequestReviewDecision.PullRequestReviewDecision) Api.Object.PullRequest
reviewDecision =
    Object.selectionForField "(Maybe Enum.PullRequestReviewDecision.PullRequestReviewDecision)" "reviewDecision" [] (Api.Enum.PullRequestReviewDecision.decoder |> Decode.nullable)


type alias ReviewRequestsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of review requests associated with the pull request.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
reviewRequests :
    (ReviewRequestsOptionalArguments -> ReviewRequestsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.ReviewRequestConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
reviewRequests fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reviewRequests" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


type alias ReviewThreadsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| The list of all review threads for this pull request.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
reviewThreads :
    (ReviewThreadsOptionalArguments -> ReviewThreadsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestReviewThreadConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
reviewThreads fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reviewThreads" optionalArgs____ object____ Basics.identity


type alias ReviewsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , states : OptionalArgument (List Api.Enum.PullRequestReviewState.PullRequestReviewState)
    , author : OptionalArgument String
    }


{-| A list of reviews associated with the pull request.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - states - A list of states to filter the reviews.
  - author - Filter by author of the review.

-}
reviews :
    (ReviewsOptionalArguments -> ReviewsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestReviewConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
reviews fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, states = Absent, author = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "states" filledInOptionals____.states (Encode.enum Api.Enum.PullRequestReviewState.toString |> Encode.list), Argument.optional "author" filledInOptionals____.author Encode.string ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "reviews" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| Identifies the state of the pull request.
-}
state : SelectionSet Api.Enum.PullRequestState.PullRequestState Api.Object.PullRequest
state =
    Object.selectionForField "Enum.PullRequestState.PullRequestState" "state" [] Api.Enum.PullRequestState.decoder


{-| A list of reviewer suggestions based on commit history and past review comments.
-}
suggestedReviewers :
    SelectionSet decodesTo Api.Object.SuggestedReviewer
    -> SelectionSet (List (Maybe decodesTo)) Api.Object.PullRequest
suggestedReviewers object____ =
    Object.selectionForCompositeField "suggestedReviewers" [] object____ (Basics.identity >> Decode.nullable >> Decode.list)


type alias TimelineOptionalArguments =
    { since : OptionalArgument Api.ScalarCodecs.DateTime
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of events, comments, commits, etc. associated with the pull request.
@deprecated `timeline` will be removed Use PullRequest.timelineItems instead. Removal on 2020-10-01 UTC.

  - since - Allows filtering timeline events by a `since` timestamp.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
timeline :
    (TimelineOptionalArguments -> TimelineOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestTimelineConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
timeline fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { since = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "since" filledInOptionals____.since (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecDateTime), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "timeline" optionalArgs____ object____ Basics.identity


type alias TimelineItemsOptionalArguments =
    { since : OptionalArgument Api.ScalarCodecs.DateTime
    , skip : OptionalArgument Int
    , itemTypes : OptionalArgument (List Api.Enum.PullRequestTimelineItemsItemType.PullRequestTimelineItemsItemType)
    , after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of events, comments, commits, etc. associated with the pull request.

  - since - Filter timeline items by a `since` timestamp.
  - skip - Skips the first _n_ elements in the list.
  - itemTypes - Filter timeline items by type.
  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
timelineItems :
    (TimelineItemsOptionalArguments -> TimelineItemsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestTimelineItemsConnection
    -> SelectionSet decodesTo Api.Object.PullRequest
timelineItems fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { since = Absent, skip = Absent, itemTypes = Absent, after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "since" filledInOptionals____.since (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecDateTime), Argument.optional "skip" filledInOptionals____.skip Encode.int, Argument.optional "itemTypes" filledInOptionals____.itemTypes (Encode.enum Api.Enum.PullRequestTimelineItemsItemType.toString |> Encode.list), Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "timelineItems" optionalArgs____ object____ Basics.identity


{-| Identifies the pull request title.
-}
title : SelectionSet String Api.Object.PullRequest
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| Identifies the pull request title rendered to HTML.
-}
titleHTML : SelectionSet Api.ScalarCodecs.Html Api.Object.PullRequest
titleHTML =
    Object.selectionForField "ScalarCodecs.Html" "titleHTML" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecHtml |> .decoder)


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.PullRequest
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The HTTP URL for this pull request.
-}
url : SelectionSet Api.ScalarCodecs.Uri Api.Object.PullRequest
url =
    Object.selectionForField "ScalarCodecs.Uri" "url" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


type alias UserContentEditsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    }


{-| A list of edits to this content.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.

-}
userContentEdits :
    (UserContentEditsOptionalArguments -> UserContentEditsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.UserContentEditConnection
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
userContentEdits fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "userContentEdits" optionalArgs____ object____ (Basics.identity >> Decode.nullable)


{-| Whether or not the viewer can apply suggestion.
-}
viewerCanApplySuggestion : SelectionSet Bool Api.Object.PullRequest
viewerCanApplySuggestion =
    Object.selectionForField "Bool" "viewerCanApplySuggestion" [] Decode.bool


{-| Check if the viewer can restore the deleted head ref.
-}
viewerCanDeleteHeadRef : SelectionSet Bool Api.Object.PullRequest
viewerCanDeleteHeadRef =
    Object.selectionForField "Bool" "viewerCanDeleteHeadRef" [] Decode.bool


{-| Whether or not the viewer can disable auto-merge
-}
viewerCanDisableAutoMerge : SelectionSet Bool Api.Object.PullRequest
viewerCanDisableAutoMerge =
    Object.selectionForField "Bool" "viewerCanDisableAutoMerge" [] Decode.bool


{-| Can the viewer edit files within this pull request.
-}
viewerCanEditFiles : SelectionSet Bool Api.Object.PullRequest
viewerCanEditFiles =
    Object.selectionForField "Bool" "viewerCanEditFiles" [] Decode.bool


{-| Whether or not the viewer can enable auto-merge
-}
viewerCanEnableAutoMerge : SelectionSet Bool Api.Object.PullRequest
viewerCanEnableAutoMerge =
    Object.selectionForField "Bool" "viewerCanEnableAutoMerge" [] Decode.bool


{-| Indicates whether the viewer can bypass branch protections and merge the pull request immediately
-}
viewerCanMergeAsAdmin : SelectionSet Bool Api.Object.PullRequest
viewerCanMergeAsAdmin =
    Object.selectionForField "Bool" "viewerCanMergeAsAdmin" [] Decode.bool


{-| Can user react to this subject
-}
viewerCanReact : SelectionSet Bool Api.Object.PullRequest
viewerCanReact =
    Object.selectionForField "Bool" "viewerCanReact" [] Decode.bool


{-| Check if the viewer is able to change their subscription status for the repository.
-}
viewerCanSubscribe : SelectionSet Bool Api.Object.PullRequest
viewerCanSubscribe =
    Object.selectionForField "Bool" "viewerCanSubscribe" [] Decode.bool


{-| Check if the current viewer can update this object.
-}
viewerCanUpdate : SelectionSet Bool Api.Object.PullRequest
viewerCanUpdate =
    Object.selectionForField "Bool" "viewerCanUpdate" [] Decode.bool


{-| Reasons why the current viewer can not update this comment.
-}
viewerCannotUpdateReasons : SelectionSet (List Api.Enum.CommentCannotUpdateReason.CommentCannotUpdateReason) Api.Object.PullRequest
viewerCannotUpdateReasons =
    Object.selectionForField "(List Enum.CommentCannotUpdateReason.CommentCannotUpdateReason)" "viewerCannotUpdateReasons" [] (Api.Enum.CommentCannotUpdateReason.decoder |> Decode.list)


{-| Did the viewer author this comment.
-}
viewerDidAuthor : SelectionSet Bool Api.Object.PullRequest
viewerDidAuthor =
    Object.selectionForField "Bool" "viewerDidAuthor" [] Decode.bool


{-| The latest review given from the viewer.
-}
viewerLatestReview :
    SelectionSet decodesTo Api.Object.PullRequestReview
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
viewerLatestReview object____ =
    Object.selectionForCompositeField "viewerLatestReview" [] object____ (Basics.identity >> Decode.nullable)


{-| The person who has requested the viewer for review on this pull request.
-}
viewerLatestReviewRequest :
    SelectionSet decodesTo Api.Object.ReviewRequest
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequest
viewerLatestReviewRequest object____ =
    Object.selectionForCompositeField "viewerLatestReviewRequest" [] object____ (Basics.identity >> Decode.nullable)


type alias ViewerMergeBodyTextOptionalArguments =
    { mergeType : OptionalArgument Api.Enum.PullRequestMergeMethod.PullRequestMergeMethod }


{-| The merge body text for the viewer and method.

  - mergeType - The merge method for the message.

-}
viewerMergeBodyText :
    (ViewerMergeBodyTextOptionalArguments -> ViewerMergeBodyTextOptionalArguments)
    -> SelectionSet String Api.Object.PullRequest
viewerMergeBodyText fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { mergeType = Absent }

        optionalArgs____ =
            [ Argument.optional "mergeType" filledInOptionals____.mergeType (Encode.enum Api.Enum.PullRequestMergeMethod.toString) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "String" "viewerMergeBodyText" optionalArgs____ Decode.string


type alias ViewerMergeHeadlineTextOptionalArguments =
    { mergeType : OptionalArgument Api.Enum.PullRequestMergeMethod.PullRequestMergeMethod }


{-| The merge headline text for the viewer and method.

  - mergeType - The merge method for the message.

-}
viewerMergeHeadlineText :
    (ViewerMergeHeadlineTextOptionalArguments -> ViewerMergeHeadlineTextOptionalArguments)
    -> SelectionSet String Api.Object.PullRequest
viewerMergeHeadlineText fillInOptionals____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { mergeType = Absent }

        optionalArgs____ =
            [ Argument.optional "mergeType" filledInOptionals____.mergeType (Encode.enum Api.Enum.PullRequestMergeMethod.toString) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForField "String" "viewerMergeHeadlineText" optionalArgs____ Decode.string


{-| Identifies if the viewer is watching, not watching, or ignoring the subscribable entity.
-}
viewerSubscription : SelectionSet (Maybe Api.Enum.SubscriptionState.SubscriptionState) Api.Object.PullRequest
viewerSubscription =
    Object.selectionForField "(Maybe Enum.SubscriptionState.SubscriptionState)" "viewerSubscription" [] (Api.Enum.SubscriptionState.decoder |> Decode.nullable)
