-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.PullRequestReviewThread exposing (..)

import Api.Enum.DiffSide
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


type alias CommentsOptionalArguments =
    { after : OptionalArgument String
    , before : OptionalArgument String
    , first : OptionalArgument Int
    , last : OptionalArgument Int
    , skip : OptionalArgument Int
    }


{-| A list of pull request comments associated with the thread.

  - after - Returns the elements in the list that come after the specified cursor.
  - before - Returns the elements in the list that come before the specified cursor.
  - first - Returns the first _n_ elements from the list.
  - last - Returns the last _n_ elements from the list.
  - skip - Skips the first _n_ elements in the list.

-}
comments :
    (CommentsOptionalArguments -> CommentsOptionalArguments)
    -> SelectionSet decodesTo Api.Object.PullRequestReviewCommentConnection
    -> SelectionSet decodesTo Api.Object.PullRequestReviewThread
comments fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { after = Absent, before = Absent, first = Absent, last = Absent, skip = Absent }

        optionalArgs____ =
            [ Argument.optional "after" filledInOptionals____.after Encode.string, Argument.optional "before" filledInOptionals____.before Encode.string, Argument.optional "first" filledInOptionals____.first Encode.int, Argument.optional "last" filledInOptionals____.last Encode.int, Argument.optional "skip" filledInOptionals____.skip Encode.int ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "comments" optionalArgs____ object____ Basics.identity


{-| The side of the diff on which this thread was placed.
-}
diffSide : SelectionSet Api.Enum.DiffSide.DiffSide Api.Object.PullRequestReviewThread
diffSide =
    Object.selectionForField "Enum.DiffSide.DiffSide" "diffSide" [] Api.Enum.DiffSide.decoder


id : SelectionSet Api.ScalarCodecs.Id Api.Object.PullRequestReviewThread
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Whether or not the thread has been collapsed (resolved)
-}
isCollapsed : SelectionSet Bool Api.Object.PullRequestReviewThread
isCollapsed =
    Object.selectionForField "Bool" "isCollapsed" [] Decode.bool


{-| Indicates whether this thread was outdated by newer changes.
-}
isOutdated : SelectionSet Bool Api.Object.PullRequestReviewThread
isOutdated =
    Object.selectionForField "Bool" "isOutdated" [] Decode.bool


{-| Whether this thread has been resolved
-}
isResolved : SelectionSet Bool Api.Object.PullRequestReviewThread
isResolved =
    Object.selectionForField "Bool" "isResolved" [] Decode.bool


{-| The line in the file to which this thread refers
-}
line : SelectionSet (Maybe Int) Api.Object.PullRequestReviewThread
line =
    Object.selectionForField "(Maybe Int)" "line" [] (Decode.int |> Decode.nullable)


{-| The original line in the file to which this thread refers.
-}
originalLine : SelectionSet (Maybe Int) Api.Object.PullRequestReviewThread
originalLine =
    Object.selectionForField "(Maybe Int)" "originalLine" [] (Decode.int |> Decode.nullable)


{-| The original start line in the file to which this thread refers (multi-line only).
-}
originalStartLine : SelectionSet (Maybe Int) Api.Object.PullRequestReviewThread
originalStartLine =
    Object.selectionForField "(Maybe Int)" "originalStartLine" [] (Decode.int |> Decode.nullable)


{-| Identifies the file path of this thread.
-}
path : SelectionSet String Api.Object.PullRequestReviewThread
path =
    Object.selectionForField "String" "path" [] Decode.string


{-| Identifies the pull request associated with this thread.
-}
pullRequest :
    SelectionSet decodesTo Api.Object.PullRequest
    -> SelectionSet decodesTo Api.Object.PullRequestReviewThread
pullRequest object____ =
    Object.selectionForCompositeField "pullRequest" [] object____ Basics.identity


{-| Identifies the repository associated with this thread.
-}
repository :
    SelectionSet decodesTo Api.Object.Repository
    -> SelectionSet decodesTo Api.Object.PullRequestReviewThread
repository object____ =
    Object.selectionForCompositeField "repository" [] object____ Basics.identity


{-| The user who resolved this thread
-}
resolvedBy :
    SelectionSet decodesTo Api.Object.User
    -> SelectionSet (Maybe decodesTo) Api.Object.PullRequestReviewThread
resolvedBy object____ =
    Object.selectionForCompositeField "resolvedBy" [] object____ (Basics.identity >> Decode.nullable)


{-| The side of the diff that the first line of the thread starts on (multi-line only)
-}
startDiffSide : SelectionSet (Maybe Api.Enum.DiffSide.DiffSide) Api.Object.PullRequestReviewThread
startDiffSide =
    Object.selectionForField "(Maybe Enum.DiffSide.DiffSide)" "startDiffSide" [] (Api.Enum.DiffSide.decoder |> Decode.nullable)


{-| The start line in the file to which this thread refers (multi-line only)
-}
startLine : SelectionSet (Maybe Int) Api.Object.PullRequestReviewThread
startLine =
    Object.selectionForField "(Maybe Int)" "startLine" [] (Decode.int |> Decode.nullable)


{-| Indicates whether the current viewer can reply to this thread.
-}
viewerCanReply : SelectionSet Bool Api.Object.PullRequestReviewThread
viewerCanReply =
    Object.selectionForField "Bool" "viewerCanReply" [] Decode.bool


{-| Whether or not the viewer can resolve this thread
-}
viewerCanResolve : SelectionSet Bool Api.Object.PullRequestReviewThread
viewerCanResolve =
    Object.selectionForField "Bool" "viewerCanResolve" [] Decode.bool


{-| Whether or not the viewer can unresolve this thread
-}
viewerCanUnresolve : SelectionSet Bool Api.Object.PullRequestReviewThread
viewerCanUnresolve =
    Object.selectionForField "Bool" "viewerCanUnresolve" [] Decode.bool
