-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.RepositoryMigration exposing (..)

import Api.Enum.MigrationState
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The Octoshift migration flag to continue on error.
-}
continueOnError : SelectionSet Bool Api.Object.RepositoryMigration
continueOnError =
    Object.selectionForField "Bool" "continueOnError" [] Decode.bool


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.RepositoryMigration
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe String) Api.Object.RepositoryMigration
databaseId =
    Object.selectionForField "(Maybe String)" "databaseId" [] (Decode.string |> Decode.nullable)


{-| The reason the migration failed.
-}
failureReason : SelectionSet (Maybe String) Api.Object.RepositoryMigration
failureReason =
    Object.selectionForField "(Maybe String)" "failureReason" [] (Decode.string |> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.RepositoryMigration
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The URL for the migration log (expires 1 day after migration completes).
-}
migrationLogUrl : SelectionSet (Maybe Api.ScalarCodecs.Uri) Api.Object.RepositoryMigration
migrationLogUrl =
    Object.selectionForField "(Maybe ScalarCodecs.Uri)" "migrationLogUrl" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder |> Decode.nullable)


{-| The Octoshift migration source.
-}
migrationSource :
    SelectionSet decodesTo Api.Object.MigrationSource
    -> SelectionSet decodesTo Api.Object.RepositoryMigration
migrationSource object____ =
    Object.selectionForCompositeField "migrationSource" [] object____ Basics.identity


{-| The target repository name.
-}
repositoryName : SelectionSet String Api.Object.RepositoryMigration
repositoryName =
    Object.selectionForField "String" "repositoryName" [] Decode.string


{-| The Octoshift migration source URL.
-}
sourceUrl : SelectionSet Api.ScalarCodecs.Uri Api.Object.RepositoryMigration
sourceUrl =
    Object.selectionForField "ScalarCodecs.Uri" "sourceUrl" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecUri |> .decoder)


{-| The Octoshift migration state.
-}
state : SelectionSet Api.Enum.MigrationState.MigrationState Api.Object.RepositoryMigration
state =
    Object.selectionForField "Enum.MigrationState.MigrationState" "state" [] Api.Enum.MigrationState.decoder
