-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.SponsorsGoal exposing (..)

import Api.Enum.SponsorsGoalKind
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A description of the goal from the maintainer.
-}
description : SelectionSet (Maybe String) Api.Object.SponsorsGoal
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| What the objective of this goal is.
-}
kind : SelectionSet Api.Enum.SponsorsGoalKind.SponsorsGoalKind Api.Object.SponsorsGoal
kind =
    Object.selectionForField "Enum.SponsorsGoalKind.SponsorsGoalKind" "kind" [] Api.Enum.SponsorsGoalKind.decoder


{-| The percentage representing how complete this goal is, between 0-100.
-}
percentComplete : SelectionSet Int Api.Object.SponsorsGoal
percentComplete =
    Object.selectionForField "Int" "percentComplete" [] Decode.int


{-| What the goal amount is. Represents an amount in USD for monthly sponsorship amount goals. Represents a count of unique sponsors for total sponsors count goals.
-}
targetValue : SelectionSet Int Api.Object.SponsorsGoal
targetValue =
    Object.selectionForField "Int" "targetValue" [] Decode.int


{-| A brief summary of the kind and target value of this goal.
-}
title : SelectionSet String Api.Object.SponsorsGoal
title =
    Object.selectionForField "String" "title" [] Decode.string
