-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.SponsorsActivity exposing (..)

import Api.Enum.SponsorsActivityAction
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| What action this activity indicates took place.
-}
action : SelectionSet Api.Enum.SponsorsActivityAction.SponsorsActivityAction Api.Object.SponsorsActivity
action =
    Object.selectionForField "Enum.SponsorsActivityAction.SponsorsActivityAction" "action" [] Api.Enum.SponsorsActivityAction.decoder


id : SelectionSet Api.ScalarCodecs.Id Api.Object.SponsorsActivity
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The tier that the sponsorship used to use, for tier change events.
-}
previousSponsorsTier :
    SelectionSet decodesTo Api.Object.SponsorsTier
    -> SelectionSet (Maybe decodesTo) Api.Object.SponsorsActivity
previousSponsorsTier object____ =
    Object.selectionForCompositeField "previousSponsorsTier" [] object____ (Basics.identity >> Decode.nullable)


{-| The user or organization who triggered this activity and was/is sponsoring the sponsorable.
-}
sponsor :
    SelectionSet decodesTo Api.Union.Sponsor
    -> SelectionSet (Maybe decodesTo) Api.Object.SponsorsActivity
sponsor object____ =
    Object.selectionForCompositeField "sponsor" [] object____ (Basics.identity >> Decode.nullable)


{-| The user or organization that is being sponsored, the maintainer.
-}
sponsorable :
    SelectionSet decodesTo Api.Interface.Sponsorable
    -> SelectionSet decodesTo Api.Object.SponsorsActivity
sponsorable object____ =
    Object.selectionForCompositeField "sponsorable" [] object____ Basics.identity


{-| The associated sponsorship tier.
-}
sponsorsTier :
    SelectionSet decodesTo Api.Object.SponsorsTier
    -> SelectionSet (Maybe decodesTo) Api.Object.SponsorsActivity
sponsorsTier object____ =
    Object.selectionForCompositeField "sponsorsTier" [] object____ (Basics.identity >> Decode.nullable)


{-| The timestamp of this event.
-}
timestamp : SelectionSet (Maybe Api.ScalarCodecs.DateTime) Api.Object.SponsorsActivity
timestamp =
    Object.selectionForField "(Maybe ScalarCodecs.DateTime)" "timestamp" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder |> Decode.nullable)
