-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.StatusContextStateCount exposing (..)

import Api.Enum.StatusState
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The number of statuses with this state.
-}
count : SelectionSet Int Api.Object.StatusContextStateCount
count =
    Object.selectionForField "Int" "count" [] Decode.int


{-| The state of a status context.
-}
state : SelectionSet Api.Enum.StatusState.StatusState Api.Object.StatusContextStateCount
state =
    Object.selectionForField "Enum.StatusState.StatusState" "state" [] Api.Enum.StatusState.decoder
