-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.StatusCheckRollupContextConnection exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The number of check runs in this rollup.
-}
checkRunCount : SelectionSet Int Api.Object.StatusCheckRollupContextConnection
checkRunCount =
    Object.selectionForField "Int" "checkRunCount" [] Decode.int


{-| Counts of check runs by state.
-}
checkRunCountsByState :
    SelectionSet decodesTo Api.Object.CheckRunStateCount
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.StatusCheckRollupContextConnection
checkRunCountsByState object____ =
    Object.selectionForCompositeField "checkRunCountsByState" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| A list of edges.
-}
edges :
    SelectionSet decodesTo Api.Object.StatusCheckRollupContextEdge
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.StatusCheckRollupContextConnection
edges object____ =
    Object.selectionForCompositeField "edges" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| A list of nodes.
-}
nodes :
    SelectionSet decodesTo Api.Union.StatusCheckRollupContext
    -> SelectionSet (Maybe (List (Maybe decodesTo))) Api.Object.StatusCheckRollupContextConnection
nodes object____ =
    Object.selectionForCompositeField "nodes" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Information to aid in pagination.
-}
pageInfo :
    SelectionSet decodesTo Api.Object.PageInfo
    -> SelectionSet decodesTo Api.Object.StatusCheckRollupContextConnection
pageInfo object____ =
    Object.selectionForCompositeField "pageInfo" [] object____ Basics.identity


{-| The number of status contexts in this rollup.
-}
statusContextCount : SelectionSet Int Api.Object.StatusCheckRollupContextConnection
statusContextCount =
    Object.selectionForField "Int" "statusContextCount" [] Decode.int


{-| Counts of status contexts by state.
-}
statusContextCountsByState :
    SelectionSet decodesTo Api.Object.StatusContextStateCount
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.StatusCheckRollupContextConnection
statusContextCountsByState object____ =
    Object.selectionForCompositeField "statusContextCountsByState" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)


{-| Identifies the total count of items in the connection.
-}
totalCount : SelectionSet Int Api.Object.StatusCheckRollupContextConnection
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int
