-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Interface.ProjectV2ItemFieldValueCommon exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


type alias Fragments decodesTo =
    { onProjectV2ItemFieldDateValue : SelectionSet decodesTo Api.Object.ProjectV2ItemFieldDateValue
    , onProjectV2ItemFieldIterationValue : SelectionSet decodesTo Api.Object.ProjectV2ItemFieldIterationValue
    , onProjectV2ItemFieldNumberValue : SelectionSet decodesTo Api.Object.ProjectV2ItemFieldNumberValue
    , onProjectV2ItemFieldSingleSelectValue : SelectionSet decodesTo Api.Object.ProjectV2ItemFieldSingleSelectValue
    , onProjectV2ItemFieldTextValue : SelectionSet decodesTo Api.Object.ProjectV2ItemFieldTextValue
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Api.Interface.ProjectV2ItemFieldValueCommon
fragments selections____ =
    Object.exhaustiveFragmentSelection
        [ Object.buildFragment "ProjectV2ItemFieldDateValue" selections____.onProjectV2ItemFieldDateValue
        , Object.buildFragment "ProjectV2ItemFieldIterationValue" selections____.onProjectV2ItemFieldIterationValue
        , Object.buildFragment "ProjectV2ItemFieldNumberValue" selections____.onProjectV2ItemFieldNumberValue
        , Object.buildFragment "ProjectV2ItemFieldSingleSelectValue" selections____.onProjectV2ItemFieldSingleSelectValue
        , Object.buildFragment "ProjectV2ItemFieldTextValue" selections____.onProjectV2ItemFieldTextValue
        ]


{-| Can be used to create a non-exhaustive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onProjectV2ItemFieldDateValue = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProjectV2ItemFieldIterationValue = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProjectV2ItemFieldNumberValue = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProjectV2ItemFieldSingleSelectValue = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onProjectV2ItemFieldTextValue = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| Identifies the date and time when the object was created.
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Interface.ProjectV2ItemFieldValueCommon
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| The actor who created the item.
-}
creator :
    SelectionSet decodesTo Api.Interface.Actor
    -> SelectionSet (Maybe decodesTo) Api.Interface.ProjectV2ItemFieldValueCommon
creator object____ =
    Object.selectionForCompositeField "creator" [] object____ (Basics.identity >> Decode.nullable)


{-| Identifies the primary key from the database.
-}
databaseId : SelectionSet (Maybe Int) Api.Interface.ProjectV2ItemFieldValueCommon
databaseId =
    Object.selectionForField "(Maybe Int)" "databaseId" [] (Decode.int |> Decode.nullable)


{-| The project field that contains this value.
-}
field :
    SelectionSet decodesTo Api.Union.ProjectV2FieldConfiguration
    -> SelectionSet decodesTo Api.Interface.ProjectV2ItemFieldValueCommon
field object____ =
    Object.selectionForCompositeField "field" [] object____ Basics.identity


id : SelectionSet Api.ScalarCodecs.Id Api.Interface.ProjectV2ItemFieldValueCommon
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The project item that contains this value.
-}
item :
    SelectionSet decodesTo Api.Object.ProjectV2Item
    -> SelectionSet decodesTo Api.Interface.ProjectV2ItemFieldValueCommon
item object____ =
    Object.selectionForCompositeField "item" [] object____ Basics.identity


{-| Identifies the date and time when the object was last updated.
-}
updatedAt : SelectionSet Api.ScalarCodecs.DateTime Api.Interface.ProjectV2ItemFieldValueCommon
updatedAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updatedAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
